### PR TITLE
Long over due pull request (Tracking, XAV,etc)

### PR DESCRIPTION
**Pull request by willt**
So this is a long overdue pull request.

I have added UPS Tracking and XAV (Address Validation) support.
I also added the other options in for Surepost instead of just option 93.
Option 92 for Surepost needs to be specified in Ounces so that was added too.
Also in UPS.pm I changed the local hashes to be attributes. I needed to do this
so I can add some custom company specific stuff into UPS.pm that isn't directly
applicable to others.

Let me know what you think.

### CODE REVIEW

**Comment by pullingshots** [comment]
Thanks William, this is great! I will review and merge as soon as possible!

**Comment by willt** [comment]
This last commit adds in street level address classification for determining if an address is Residential or Commercial. Handy for sure post since it's residential only.

**Comment by pullingshots** [comment]
All changes have been merged except for Tracking.

UPS Tracking will be added along with FedEx, see  issue #42

**Comment by pullingshots** [comment]
@willt I have finally merged in the tracking with commit 7d6cdd5311

**Pull request closed without merging**
